services:
  app:
    build: .
    container_name: x_clone_app
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - deps_data:/app/deps
      - _build_data:/app/_build
    environment:
      DATABASE_URL: "ecto://postgres:postgres@db/x_clone_dev"
      PHX_HOST: "localhost"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: x_clone_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: x_clone_dev
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  deps_data:
  _build_data:
  db_data:
